source 'https://rubygems.org'

ruby '3.3.5'

gem 'minitest', '~> 5.17'
gem 'solargraph'

gem 'ripper-tags', '~> 0.9.0'

gem 'debug', '~> 1.7'

gem 'syntax_tree', '~> 6.2'

gem 'standard'

gem 'rubocop', '~> 1.67'
